openapi: 3.1.0
info:
  title: auth-servis API
  description: Authentication API
  version: 1.1.2 
servers:
  - url: http://localhost:3000
  - url: https://localhost:3000

paths:
  /registration:
    post:
      summary: Регистрация пользователя
      description: Создание нового пользователя
      parameters:
        - in: header
          name: username
          required: true
          schema:
            type: string
          description: Имя пользователя
        - in: header
          name: passwd
          required: true
          schema:
            type: string
          description: Пароль пользователя
      responses:
        '201':
          description: Пользователь создан успешно
        '400':
          description: Некорректные данные

  /login:
    get:
      summary: Вход в систему
      description: Аутентификация пользователя
      parameters:
        - in: header
          name: username
          required: true
          schema:
            type: string
          description: Имя пользователя
        - in: header
          name: passwd
          required: true
          schema:
            type: string
          description: Пароль пользователя
      responses:
        '200':
          description: Успешная аутентификация
        '401':
          description: Неправильные учетные данные
  
  /logout:
    post:
      summary: Выход из системы
      description: Завершение сессии пользователя
      parameters:
        - in: header
          name: refresh-token
          required: true
          schema:
            type: string
          description: refresh токен пользователя
      responses:
        '200':
          description: Выход выполнен успешно
        '401':
          description: Неавторизованный доступ

  /updateaccesst:
    post:
      summary: Обновление токена доступа
      description: Обновление access токена пользователя
      parameters:
        - in: header
          name: refresh-token
          required: true
          schema:
            type: string
          description: refresh токен пользователя
      responses:
        '200':
          description: Токен обновлен успешно
        '401':
          description: Неавторизованный доступ

